import pool from '../../db.js';

export const getOrders = async (req,res) =>{
    try {
        const client = await pool.connect();
        const result = await client.query(`
            SELECT *
            FROM OrderLab
          `);
        
        const OrderLabID = result.rows.map(row => row.orderlab_id);
        const DoctorID = result.rows.map(row => row.physician_id);
        const CardID = result.rows.map(row => row.card_id);
        const Emergency = result.rows.map(row => row.emergency_case);
        const OrderDate = result.rows.map(row => row.orderdate);
        const OrderStatus = result.rows.map(row => row.orderstatus);

        const MemberTable = {
            OrderLabID,
            DoctorID,
            CardID,
            Emergency,
            OrderDate,
            OrderStatus
        }
        
        res.json(MemberTable);
        client.release();
    
      } catch (err) {
        console.error(err);
        res.send('Error ' + err);
      }
}

//สร้าง orderlab
export const createOrderLab = async (req,res) =>{
    const {
        physician_id,
        card_id,
        physician_name,
        emergency_case,
        orderdate,
        orderstatus
    } = req.body;

    try {
        const client = await pool.connect();
        console.log('Connected to database');  // ตรวจสอบการเชื่อมต่อ

        const ress = await client.query('SELECT MAX(orderlab_id) AS latest_id FROM orderlab');
        const latestId = ress.rows[0].latest_id;
        const newId = (latestId || 0) + 1;

        const query = `
            INSERT INTO orderlab (
                orderlab_id,
                physician_id,
                card_id,
                physician_name,
                emergency_case,
                orderdate,
                orderlabstatus
            ) VALUES ($1, $2, $3, $4, $5, $6, $7) RETURNING *;
        `;

        // Log the values being inserted
        const values = [
            newId,
            physician_id,
            card_id,
            physician_name || null,
            emergency_case || "N",
            orderdate,
            orderstatus || "Create OrderLab"
        ];
        console.log('Inserting values:', values);
        
        const result = await client.query(query, values);
        res.status(201).json({
            success: true,
            data: result.rows[0],  // คืนค่าข้อมูลสมาชิกที่ถูกสร้าง
        });

        client.release();
        return { newId,card_id };

    } catch (error) {
        console.error('Error creating order:', error);  // ตรวจสอบข้อผิดพลาดจากการ insert ข้อมูล
        res.status(500).json({
            success: false,
            message: 'Error creating order',
            error: error.message,
        });
    }
}

//สร้าง orderselection แบบรับค่า req,body
export const createOrderSelectionn = async (req,res) => {
    const {
        orderlab_id,
        member_id,
        card_id,
        CBC,
        Hematocrit,
        ESR,
        PT_INR,
        aPTT,
        TT,
        ABO_gr,
        Rh_gr,
        Urine_Analysis,
        Pregnancy_Test,
        Stool_Exam,
        Occult_Blood,
        Wet_Smear,
        RPR,
        TPHA,
        HIV_Ag_Ab,
        HBsAg,
        Anti_HBs,
        Anti_HCV,
        Anti_HBc_Total,
        Anti_HBc_IgM,
        Anti_HAV_IgM,
        HBeAg,
        Melioid_titer,
        CA_125,
        Ca_15_3,
        CA_19_9,
        AFP,
        CEA,
        PSA,
        B_HCG,
        Free_T4,
        Free_T3,
        TSH,
        Cortisol,
        Blood_Sugar,
        BUN,
        Creatinine,
        GFR,
        Uric_acid,
        Electrolyte_Na_Cl_K_CO2,
        HbAlC,
        Calcium,
        Phosphorus,
        Magnesium,
        Serum_Iron,
        TIBC,
        Ferritin,
        GGT,
        Cholesterol_LFT,
        Total_protein,
        Albumin,
        Direct_bilirubin,
        Total_bilirubin,
        AST_SGOT,
        ALT_SGPT,
        Alkaline_Phosphatase,
        Cholesterol_Lupid_Profile,
        Triglyceride,
        HDL_Cholesterol,
        LDL_Cholesterol,
        LDL_Direct,
        Creatinine_24_hrs,
        Protein_24_hrs,
        Creatinine_random,
        Protein_random,
        Microalbumin,
        Urine_Na_K_Cl,
        AFB_stain,
        Gram_stain,
        Hemo_I,
        Hemo_II,
        Sputum,
        PUS,
        Urine,
        RSC,
        Fluid,
        CSF,
        LDH,
        CPK,
        Amylase_Urine,
        Amylase_Serum,
        ADA_Urine,
        ADA_Serum,
        Osmolarity_Urine,
        Osmolarity_Serum,
        Ketone,
        Lipase,
        Transferin,
        Parathyroid,
        L_Lactate,
        Troponin_I,
        Prolactin,
        LH,
        FSH,
        Estradiol_E2,
        Insulin,
        Testosterone,
        Thyroglobulin,
        Anti_Thyroglobulin,
        Microsomal_Ab,
        Phenobarbital,
        PhenyItoin,
        Digoxin,
        Valproic,
        Carbamazepine,
        Vancomycin,
        NT_ProBNP,
        Chromosome_Study,
        Aldosterone,
        Renin,
        Anti_Smooth_Muscle,
        C_peptide,
        JAK2_gene_Mutation,
        HLA_B_5801,
        TSH_Recceptor_Ab,
        ANA_Profile,
        Vitamin_B12,
        Folate,
        Urine_VMA,
        Chikungunya_IgG_IgM,
        Rheumatoid_factor,
        C_Reactive_Protein,
        ASO,
        ANA_ANF_FANA,
        Anti_ds_DNA,
        Anti_Smith,
        Beta_1_C_C3c,
        C4_Complement,
        Crypto_Ag,
        Dengue_Ag_Ab,
        Scrub_typhus,
        Vitamin_D,
        HBV_Viral_load,
        HCV_Viral_load,
        HSV_PCR,
        CMV_PCR,
        TB_PCR,
        Anti_CCP,
        Anti_Car_IgG_IgM,
        Beta2_IgG_IgM,
        VDRL_CSF,
        D_dimer,
        Lupus_anticoagulant,
        LE_cell,
        Fetal_cell,
        OF_Test,
        DCIP,
        G_6_PD,
        Reticulocyte,
        Inclusion_body,
        Heinz_body,
        Hb_Typing,
        Anti_Cardiolipin_IgA,
        Beta2Glycoprotein_IgA,
        Anti_HAV_Total,
        Anti_HAB_IgG,
        Anti_HBe,
        Anti_thrombin_III,
        Protein_C,
        Protein_S,
        Anti_DNaseB,
        TB_culture
    } = req.body;

    try {
        const client = await pool.connect();
        console.log('Connected to database');  // ตรวจสอบการเชื่อมต่อ

        const query = `
            INSERT INTO orderselection (
                orderlab_id,
                member_id,
                card_id,
                CBC,
                Hematocrit,
                ESR,
                PT_INR,
                aPTT,
                TT,
                ABO_gr,
                Rh_gr,
                Urine_Analysis,
                Pregnancy_Test,
                Stool_Exam,
                Occult_Blood,
                Wet_Smear,
                RPR,
                TPHA,
                HIV_Ag_Ab,
                HBsAg,
                Anti_HBs,
                Anti_HCV,
                Anti_HBc_Total,
                Anti_HBc_IgM,
                Anti_HAV_IgM,
                HBeAg,
                Melioid_titer,
                CA_125,
                Ca_15_3,
                CA_19_9,
                AFP,
                CEA,
                PSA,
                B_HCG,
                Free_T4,
                Free_T3,
                TSH,
                Cortisol,
                Blood_Sugar,
                BUN,
                Creatinine,
                GFR,
                Uric_acid,
                Electrolyte_Na_Cl_K_CO2,
                HbAlC,
                Calcium,
                Phosphorus,
                Magnesium,
                Serum_Iron,
                TIBC,
                Ferritin,
                GGT,
                Cholesterol_LFT,
                Total_protein,
                Albumin,
                Direct_bilirubin,
                Total_bilirubin,
                AST_SGOT,
                ALT_SGPT,
                Alkaline_Phosphatase,
                Cholesterol_Lupid_Profile,
                Triglyceride,
                HDL_Cholesterol,
                LDL_Cholesterol,
                LDL_Direct,
                Creatinine_24_hrs,
                Protein_24_hrs,
                Creatinine_random,
                Protein_random,
                Microalbumin,
                Urine_Na_K_Cl,
                AFB_stain,
                Gram_stain,
                Hemo_I,
                Hemo_II,
                Sputum,
                PUS,
                Urine,
                RSC,
                Fluid,
                CSF,
                LDH,
                CPK,
                Amylase_Urine,
                Amylase_Serum,
                ADA_Urine,
                ADA_Serum,
                Osmolarity_Urine,
                Osmolarity_Serum,
                Ketone,
                Lipase,
                Transferin,
                Parathyroid,
                L_Lactate,
                Troponin_I,
                Prolactin,
                LH,
                FSH,
                Estradiol_E2,
                Insulin,
                Testosterone,
                Thyroglobulin,
                Anti_Thyroglobulin,
                Microsomal_Ab,
                Phenobarbital,
                PhenyItoin,
                Digoxin,
                Valproic,
                Carbamazepine,
                Vancomycin,
                NT_ProBNP,
                Chromosome_Study,
                Aldosterone,
                Renin,
                Anti_Smooth_Muscle,
                C_peptide,
                JAK2_gene_Mutation,
                HLA_B_5801,
                TSH_Recceptor_Ab,
                ANA_Profile,
                Vitamin_B12,
                Folate,
                Urine_VMA,
                Chikungunya_IgG_IgM,
                Rheumatoid_factor,
                C_Reactive_Protein,
                ASO,
                ANA_ANF_FANA,
                Anti_ds_DNA,
                Anti_Smith,
                Beta_1_C_C3c,
                C4_Complement,
                Crypto_Ag,
                Dengue_Ag_Ab,
                Scrub_typhus,
                Vitamin_D,
                HBV_Viral_load,
                HCV_Viral_load,
                HSV_PCR,
                CMV_PCR,
                TB_PCR,
                Anti_CCP,
                Anti_Car_IgG_IgM,
                Beta2_IgG_IgM,
                VDRL_CSF,
                D_dimer,
                Lupus_anticoagulant,
                LE_cell,
                Fetal_cell,
                OF_Test,
                DCIP,
                G_6_PD,
                Reticulocyte,
                Inclusion_body,
                Heinz_body,
                Hb_Typing,
                Anti_Cardiolipin_IgA,
                Beta2Glycoprotein_IgA,
                Anti_HAV_Total,
                Anti_HAB_IgG,
                Anti_HBe,
                Anti_thrombin_III,
                Protein_C,
                Protein_S,
                Anti_DNaseB,
                TB_culture
            ) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, 
                $11, $12, $13, $14, $15, $16, $17, $18, $19, $20, 
                $21, $22, $23, $24, $25, $26, $27, $28, $29, $30, 
                $31, $32, $33, $34, $35, $36, $37, $38, $39, $40, 
                $41, $42, $43, $44, $45, $46, $47, $48, $49, $50, 
                $51, $52, $53, $54, $55, $56, $57, $58, $59, $60, 
                $61, $62, $63, $64, $65, $66, $67, $68, $69, $70, 
                $71, $72, $73, $74, $75, $76, $77, $78, $79, $80, 
                $81, $82, $83, $84, $85, $86, $87, $88, $89, $90, 
                $91, $92, $93, $94, $95, $96, $97, $98, $99, $100, 
                $101, $102, $103, $104, $105, $106, $107, $108, $109, $110, 
                $111, $112, $113, $114, $115, $116, $117, $118, $119, $120, 
                $121, $122, $123, $124, $125, $126, $127, $128, $129, $130, 
                $131, $132, $133, $134, $135, $136, $137, $138, $139, $140, 
                $141, $142, $143, $144, $145, $146, $147, $148, $149, $150, 
                $151, $152, $153, $154, $155, $156, $157, $158, $159, $160, 
                $161, $162, $163, $164, $165, $166) RETURNING *;
        `;

        // Log the values being inserted
        const values = [
            orderlab_id,
            member_id || null,
            card_id,
            CBC || "F",
            Hematocrit || "F",
            ESR || "F",
            PT_INR || "F",
            aPTT || "F",
            TT || "F",
            ABO_gr || "F",
            Rh_gr || "F",
            Urine_Analysis || "F",
            Pregnancy_Test || "F",
            Stool_Exam || "F",
            Occult_Blood || "F",
            Wet_Smear || "F",
            RPR || "F",
            TPHA || "F",
            HIV_Ag_Ab || "F",
            HBsAg || "F",
            Anti_HBs || "F",
            Anti_HCV || "F",
            Anti_HBc_Total || "F",
            Anti_HBc_IgM || "F",
            Anti_HAV_IgM || "F",
            HBeAg || "F",
            Melioid_titer || "F",
            CA_125 || "F",
            Ca_15_3 || "F",
            CA_19_9 || "F",
            AFP || "F",
            CEA || "F",
            PSA || "F",
            B_HCG || "F",
            Free_T4 || "F",
            Free_T3 || "F",
            TSH || "F",
            Cortisol || "F",
            Blood_Sugar || "F",
            BUN || "F",
            Creatinine || "F",
            GFR || "F",
            Uric_acid || "F",
            Electrolyte_Na_Cl_K_CO2 || "F",
            HbAlC || "F",
            Calcium || "F",
            Phosphorus || "F",
            Magnesium || "F",
            Serum_Iron || "F",
            TIBC || "F",
            Ferritin || "F",
            GGT || "F",
            Cholesterol_LFT || "F",
            Total_protein || "F",
            Albumin || "F",
            Direct_bilirubin || "F",
            Total_bilirubin || "F",
            AST_SGOT || "F",
            ALT_SGPT || "F",
            Alkaline_Phosphatase || "F",
            Cholesterol_Lupid_Profile || "F",
            Triglyceride || "F",
            HDL_Cholesterol || "F",
            LDL_Cholesterol || "F",
            LDL_Direct || "F",
            Creatinine_24_hrs || "F",
            Protein_24_hrs || "F",
            Creatinine_random || "F",
            Protein_random || "F",
            Microalbumin || "F",
            Urine_Na_K_Cl || "F",
            AFB_stain || "F",
            Gram_stain || "F",
            Hemo_I || "F",
            Hemo_II || "F",
            Sputum || "F",
            PUS || "F",
            Urine || "F",
            RSC || "F",
            Fluid || "F",
            CSF || "F",
            LDH || "F",
            CPK || "F",
            Amylase_Urine || "F",
            Amylase_Serum || "F",
            ADA_Urine || "F",
            ADA_Serum || "F",
            Osmolarity_Urine || "F",
            Osmolarity_Serum || "F",
            Ketone || "F",
            Lipase || "F",
            Transferin || "F",
            Parathyroid || "F",
            L_Lactate || "F",
            Troponin_I || "F",
            Prolactin || "F",
            LH || "F",
            FSH || "F",
            Estradiol_E2 || "F",
            Insulin || "F",
            Testosterone || "F",
            Thyroglobulin || "F",
            Anti_Thyroglobulin || "F",
            Microsomal_Ab || "F",
            Phenobarbital || "F",
            PhenyItoin || "F",
            Digoxin || "F",
            Valproic || "F",
            Carbamazepine || "F",
            Vancomycin || "F",
            NT_ProBNP || "F",
            Chromosome_Study || "F",
            Aldosterone || "F",
            Renin || "F",
            Anti_Smooth_Muscle || "F",
            C_peptide || "F",
            JAK2_gene_Mutation || "F",
            HLA_B_5801 || "F",
            TSH_Recceptor_Ab || "F",
            ANA_Profile || "F",
            Vitamin_B12 || "F",
            Folate || "F",
            Urine_VMA || "F",
            Chikungunya_IgG_IgM || "F",
            Rheumatoid_factor || "F",
            C_Reactive_Protein || "F",
            ASO || "F",
            ANA_ANF_FANA || "F",
            Anti_ds_DNA || "F",
            Anti_Smith || "F",
            Beta_1_C_C3c || "F",
            C4_Complement || "F",
            Crypto_Ag || "F",
            Dengue_Ag_Ab || "F",
            Scrub_typhus || "F",
            Vitamin_D || "F",
            HBV_Viral_load || "F",
            HCV_Viral_load || "F",
            HSV_PCR || "F",
            CMV_PCR || "F",
            TB_PCR || "F",
            Anti_CCP || "F",
            Anti_Car_IgG_IgM || "F",
            Beta2_IgG_IgM || "F",
            VDRL_CSF || "F",
            D_dimer || "F",
            Lupus_anticoagulant || "F",
            LE_cell || "F",
            Fetal_cell || "F",
            OF_Test || "F",
            DCIP || "F",
            G_6_PD || "F",
            Reticulocyte || "F",
            Inclusion_body || "F",
            Heinz_body || "F",
            Hb_Typing || "F",
            Anti_Cardiolipin_IgA || "F",
            Beta2Glycoprotein_IgA || "F",
            Anti_HAV_Total || "F",
            Anti_HAB_IgG || "F",
            Anti_HBe || "F",
            Anti_thrombin_III || "F",
            Protein_C || "F",
            Protein_S || "F",
            Anti_DNaseB || "F",
            TB_culture || "F"

        ];
        console.log('Inserting values:', values);

        const result = await client.query(query, values);
        res.status(201).json({
            success: true,
            data: result.rows[0],  // คืนค่าข้อมูลสมาชิกที่ถูกสร้าง
        });

        client.release();
        return { newId,card_id };

    } catch (error) {
        console.error('Error creating orderselection:', error);  // ตรวจสอบข้อผิดพลาดจากการ insert ข้อมูล
        res.status(500).json({
            success: false,
            message: 'Error creating orderselection',
            error: error.message,
        });
    }
}

//สร้าง orderselection แบบรับค่า newId(orderlab_id) มา
export const createOrderSelection = async (newId,card_id,res) => {
    try {
        const client = await pool.connect();
        console.log('Connected to database');  // ตรวจสอบการเชื่อมต่อ

        const query = `
            INSERT INTO orderselection (
                orderlab_id,
                member_id,
                card_id,
                CBC,
                Hematocrit,
                ESR,
                PT_INR,
                aPTT,
                TT,
                ABO_gr,
                Rh_gr,
                Urine_Analysis,
                Pregnancy_Test,
                Stool_Exam,
                Occult_Blood,
                Wet_Smear,
                RPR,
                TPHA,
                HIV_Ag_Ab,
                HBsAg,
                Anti_HBs,
                Anti_HCV,
                Anti_HBc_Total,
                Anti_HBc_IgM,
                Anti_HAV_IgM,
                HBeAg,
                Melioid_titer,
                CA_125,
                Ca_15_3,
                CA_19_9,
                AFP,
                CEA,
                PSA,
                B_HCG,
                Free_T4,
                Free_T3,
                TSH,
                Cortisol,
                Blood_Sugar,
                BUN,
                Creatinine,
                GFR,
                Uric_acid,
                Electrolyte_Na_Cl_K_CO2,
                HbAlC,
                Calcium,
                Phosphorus,
                Magnesium,
                Serum_Iron,
                TIBC,
                Ferritin,
                GGT,
                Cholesterol_LFT,
                Total_protein,
                Albumin,
                Direct_bilirubin,
                Total_bilirubin,
                AST_SGOT,
                ALT_SGPT,
                Alkaline_Phosphatase,
                Cholesterol_Lupid_Profile,
                Triglyceride,
                HDL_Cholesterol,
                LDL_Cholesterol,
                LDL_Direct,
                Creatinine_24_hrs,
                Protein_24_hrs,
                Creatinine_random,
                Protein_random,
                Microalbumin,
                Urine_Na_K_Cl,
                AFB_stain,
                Gram_stain,
                Hemo_I,
                Hemo_II,
                Sputum,
                PUS,
                Urine,
                RSC,
                Fluid,
                CSF,
                LDH,
                CPK,
                Amylase_Urine,
                Amylase_Serum,
                ADA_Urine,
                ADA_Serum,
                Osmolarity_Urine,
                Osmolarity_Serum,
                Ketone,
                Lipase,
                Transferin,
                Parathyroid,
                L_Lactate,
                Troponin_I,
                Prolactin,
                LH,
                FSH,
                Estradiol_E2,
                Insulin,
                Testosterone,
                Thyroglobulin,
                Anti_Thyroglobulin,
                Microsomal_Ab,
                Phenobarbital,
                PhenyItoin,
                Digoxin,
                Valproic,
                Carbamazepine,
                Vancomycin,
                NT_ProBNP,
                Chromosome_Study,
                Aldosterone,
                Renin,
                Anti_Smooth_Muscle,
                C_peptide,
                JAK2_gene_Mutation,
                HLA_B_5801,
                TSH_Recceptor_Ab,
                ANA_Profile,
                Vitamin_B12,
                Folate,
                Urine_VMA,
                Chikungunya_IgG_IgM,
                Rheumatoid_factor,
                C_Reactive_Protein,
                ASO,
                ANA_ANF_FANA,
                Anti_ds_DNA,
                Anti_Smith,
                Beta_1_C_C3c,
                C4_Complement,
                Crypto_Ag,
                Dengue_Ag_Ab,
                Scrub_typhus,
                Vitamin_D,
                HBV_Viral_load,
                HCV_Viral_load,
                HSV_PCR,
                CMV_PCR,
                TB_PCR,
                Anti_CCP,
                Anti_Car_IgG_IgM,
                Beta2_IgG_IgM,
                VDRL_CSF,
                D_dimer,
                Lupus_anticoagulant,
                LE_cell,
                Fetal_cell,
                OF_Test,
                DCIP,
                G_6_PD,
                Reticulocyte,
                Inclusion_body,
                Heinz_body,
                Hb_Typing,
                Anti_Cardiolipin_IgA,
                Beta2Glycoprotein_IgA,
                Anti_HAV_Total,
                Anti_HAB_IgG,
                Anti_HBe,
                Anti_thrombin_III,
                Protein_C,
                Protein_S,
                Anti_DNaseB,
                TB_culture
            ) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, 
                $11, $12, $13, $14, $15, $16, $17, $18, $19, $20, 
                $21, $22, $23, $24, $25, $26, $27, $28, $29, $30, 
                $31, $32, $33, $34, $35, $36, $37, $38, $39, $40, 
                $41, $42, $43, $44, $45, $46, $47, $48, $49, $50, 
                $51, $52, $53, $54, $55, $56, $57, $58, $59, $60, 
                $61, $62, $63, $64, $65, $66, $67, $68, $69, $70, 
                $71, $72, $73, $74, $75, $76, $77, $78, $79, $80, 
                $81, $82, $83, $84, $85, $86, $87, $88, $89, $90, 
                $91, $92, $93, $94, $95, $96, $97, $98, $99, $100, 
                $101, $102, $103, $104, $105, $106, $107, $108, $109, $110, 
                $111, $112, $113, $114, $115, $116, $117, $118, $119, $120, 
                $121, $122, $123, $124, $125, $126, $127, $128, $129, $130, 
                $131, $132, $133, $134, $135, $136, $137, $138, $139, $140, 
                $141, $142, $143, $144, $145, $146, $147, $148, $149, $150, 
                $151, $152, $153, $154, $155, $156, $157, $158, $159, $160, 
                $161, $162, $163, $164, $165, $166) RETURNING *;
        `;

        // Log the values being inserted
        const values = [
            newId,
            null,
            card_id,
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F",
            "F"

        ];
        console.log('Inserting values:', values);

        const result = await client.query(query, values);
        res.status(201).json({
            success: true,
            data: result.rows[0],  // คืนค่าข้อมูลสมาชิกที่ถูกสร้าง
        });

        client.release();

    } catch (error) {
        console.error('Error creating orderselection:', error);  // ตรวจสอบข้อผิดพลาดจากการ insert ข้อมูล
        res.status(500).json({
            success: false,
            message: 'Error creating orderselection',
            error: error.message,
        });
    }
}

//edit orderselection แบบ api ตรงๆ
export const editorderselection = async (req,res) => {
    const { orderlab_id } = req.params;
    const {
        CBC,
        Hematocrit,
        ESR,
        PT_INR,
        aPTT,
        TT,
        ABO_gr,
        Rh_gr,
        Urine_Analysis,
        Pregnancy_Test,
        Stool_Exam,
        Occult_Blood,
        Wet_Smear,
        RPR,
        TPHA,
        HIV_Ag_Ab,
        HBsAg,
        Anti_HBs,
        Anti_HCV,
        Anti_HBc_Total,
        Anti_HBc_IgM,
        Anti_HAV_IgM,
        HBeAg,
        Melioid_titer,
        CA_125,
        Ca_15_3,
        CA_19_9,
        AFP,
        CEA,
        PSA,
        B_HCG,
        Free_T4,
        Free_T3,
        TSH,
        Cortisol,
        Blood_Sugar,
        BUN,
        Creatinine,
        GFR,
        Uric_acid,
        Electrolyte_Na_Cl_K_CO2,
        HbAlC,
        Calcium,
        Phosphorus,
        Magnesium,
        Serum_Iron,
        TIBC,
        Ferritin,
        GGT,
        Cholesterol_LFT,
        Total_protein,
        Albumin,
        Direct_bilirubin,
        Total_bilirubin,
        AST_SGOT,
        ALT_SGPT,
        Alkaline_Phosphatase,
        Cholesterol_Lupid_Profile,
        Triglyceride,
        HDL_Cholesterol,
        LDL_Cholesterol,
        LDL_Direct,
        Creatinine_24_hrs,
        Protein_24_hrs,
        Creatinine_random,
        Protein_random,
        Microalbumin,
        Urine_Na_K_Cl,
        AFB_stain,
        Gram_stain,
        Hemo_I,
        Hemo_II,
        Sputum,
        PUS,
        Urine,
        RSC,
        Fluid,
        CSF,
        LDH,
        CPK,
        Amylase_Urine,
        Amylase_Serum,
        ADA_Urine,
        ADA_Serum,
        Osmolarity_Urine,
        Osmolarity_Serum,
        Ketone,
        Lipase,
        Transferin,
        Parathyroid,
        L_Lactate,
        Troponin_I,
        Prolactin,
        LH,
        FSH,
        Estradiol_E2,
        Insulin,
        Testosterone,
        Thyroglobulin,
        Anti_Thyroglobulin,
        Microsomal_Ab,
        Phenobarbital,
        PhenyItoin,
        Digoxin,
        Valproic,
        Carbamazepine,
        Vancomycin,
        NT_ProBNP,
        Chromosome_Study,
        Aldosterone,
        Renin,
        Anti_Smooth_Muscle,
        C_peptide,
        JAK2_gene_Mutation,
        HLA_B_5801,
        TSH_Recceptor_Ab,
        ANA_Profile,
        Vitamin_B12,
        Folate,
        Urine_VMA,
        Chikungunya_IgG_IgM,
        Rheumatoid_factor,
        C_Reactive_Protein,
        ASO,
        ANA_ANF_FANA,
        Anti_ds_DNA,
        Anti_Smith,
        Beta_1_C_C3c,
        C4_Complement,
        Crypto_Ag,
        Dengue_Ag_Ab,
        Scrub_typhus,
        Vitamin_D,
        HBV_Viral_load,
        HCV_Viral_load,
        HSV_PCR,
        CMV_PCR,
        TB_PCR,
        Anti_CCP,
        Anti_Car_IgG_IgM,
        Beta2_IgG_IgM,
        VDRL_CSF,
        D_dimer,
        Lupus_anticoagulant,
        LE_cell,
        Fetal_cell,
        OF_Test,
        DCIP,
        G_6_PD,
        Reticulocyte,
        Inclusion_body,
        Heinz_body,
        Hb_Typing,
        Anti_Cardiolipin_IgA,
        Beta2Glycoprotein_IgA,
        Anti_HAV_Total,
        Anti_HAB_IgG,
        Anti_HBe,
        Anti_thrombin_III,
        Protein_C,
        Protein_S,
        Anti_DNaseB,
        TB_culture
    } = req.body;

    try {
        const query = `
            UPDATE orderselection
            SET
                CBC = $1,
                Hematocrit = $2,
                ESR = $3,
                PT_INR = $4,
                aPTT = $5,
                TT = $6,
                ABO_gr = $7,
                Rh_gr = $8,
                Urine_Analysis = $9,
                Pregnancy_Test = $10,
                Stool_Exam = $11,
                Occult_Blood = $12,
                Wet_Smear = $13,
                RPR = $14,
                TPHA = $15,
                HIV_Ag_Ab = $16,
                HBsAg = $17,
                Anti_HBs = $18,
                Anti_HCV = $19 ,
                Anti_HBc_Total = $20,
                Anti_HBc_IgM = $21,
                Anti_HAV_IgM = $22,
                HBeAg = $23,
                Melioid_titer = $24,
                CA_125 = $25,
                Ca_15_3 = $26,
                CA_19_9 = $27,
                AFP = $28,
                CEA = $29,
                PSA = $30,
                B_HCG = $31,
                Free_T4 = $32,
                Free_T3 = $33,
                TSH = $34,
                Cortisol = $35,
                Blood_Sugar = $36,
                BUN = $37,
                Creatinine = $38,
                GFR = $39,
                Uric_acid = $40,
                Electrolyte_Na_Cl_K_CO2 = $41,
                HbAlC = $42,
                Calcium = $43,
                Phosphorus = $44,
                Magnesium = $45,
                Serum_Iron = $46,
                TIBC = $47,
                Ferritin = $48,
                GGT = $49,
                Cholesterol_LFT = $50,
                Total_protein = $51,
                Albumin = $52,
                Direct_bilirubin = $53,
                Total_bilirubin = $54,
                AST_SGOT = $55,
                ALT_SGPT = $56,
                Alkaline_Phosphatase = $57,
                Cholesterol_Lupid_Profile = $58,
                Triglyceride = $59,
                HDL_Cholesterol = $60,
                LDL_Cholesterol = $61,
                LDL_Direct = $62,
                Creatinine_24_hrs = $63,
                Protein_24_hrs = $64,
                Creatinine_random = $65,
                Protein_random = $66,
                Microalbumin = $67,
                Urine_Na_K_Cl = $68,
                AFB_stain = $69,
                Gram_stain = $70,
                Hemo_I = $71,
                Hemo_II = $72,
                Sputum = $73,
                PUS = $74,
                Urine = $75,
                RSC = $76,
                Fluid = $77,
                CSF = $78,
                LDH = $79,
                CPK = $80,
                Amylase_Urine = $81,
                Amylase_Serum = $82,
                ADA_Urine = $83,
                ADA_Serum = $84,
                Osmolarity_Urine = $85,
                Osmolarity_Serum = $86,
                Ketone = $87,
                Lipase = $88,
                Transferin = $89,
                Parathyroid = $90,
                L_Lactate = $91,
                Troponin_I = $92,
                Prolactin = $93,
                LH = $94,
                FSH = $95,
                Estradiol_E2 = $96,
                Insulin = $97,
                Testosterone = $98,
                Thyroglobulin = $99,
                Anti_Thyroglobulin = $100,
                Microsomal_Ab = $101,
                Phenobarbital = $102,
                PhenyItoin = $103,
                Digoxin = $104,
                Valproic = $105,
                Carbamazepine = $106,
                Vancomycin = $107,
                NT_ProBNP = $108,
                Chromosome_Study = $109,
                Aldosterone = $110,
                Renin = $111,
                Anti_Smooth_Muscle = $112,
                C_peptide = $113,
                JAK2_gene_Mutation = $114,
                HLA_B_5801 = $115,
                TSH_Recceptor_Ab = $116,
                ANA_Profile = $117,
                Vitamin_B12 = $118,
                Folate = $119,
                Urine_VMA = $120,
                Chikungunya_IgG_IgM = $121,
                Rheumatoid_factor = $122,
                C_Reactive_Protein = $123,
                ASO = $124,
                ANA_ANF_FANA = $125,
                Anti_ds_DNA = $126,
                Anti_Smith = $127,
                Beta_1_C_C3c = $128,
                C4_Complement = $129,
                Crypto_Ag = $130,
                Dengue_Ag_Ab = $131,
                Scrub_typhus = $132,
                Vitamin_D = $133,
                HBV_Viral_load = $134,
                HCV_Viral_load = $135,
                HSV_PCR = $136,
                CMV_PCR = $137,
                TB_PCR = $138,
                Anti_CCP = $139,
                Anti_Car_IgG_IgM = $140,
                Beta2_IgG_IgM = $141,
                VDRL_CSF = $142,
                D_dimer = $143,
                Lupus_anticoagulant = $144,
                LE_cell = $145,
                Fetal_cell = $146,
                OF_Test = $147,
                DCIP = $148,
                G_6_PD = $149,
                Reticulocyte = $150,
                Inclusion_body = $151,
                Heinz_body = $152,
                Hb_Typing = $153,
                Anti_Cardiolipin_IgA = $154,
                Beta2Glycoprotein_IgA = $155,
                Anti_HAV_Total = $156,
                Anti_HAB_IgG = $157,
                Anti_HBe = $158,
                Anti_thrombin_III = $159,
                Protein_C = $160,
                Protein_S = $161,
                Anti_DNaseB = $162,
                TB_culture = $163
            WHERE orderlab_id = $164
            RETURNING *;
        `;

        const values = [
            CBC,
            Hematocrit,
            ESR,
            PT_INR,
            aPTT,
            TT,
            ABO_gr,
            Rh_gr,
            Urine_Analysis,
            Pregnancy_Test,
            Stool_Exam,
            Occult_Blood,
            Wet_Smear,
            RPR,
            TPHA,
            HIV_Ag_Ab,
            HBsAg,
            Anti_HBs,
            Anti_HCV,
            Anti_HBc_Total,
            Anti_HBc_IgM,
            Anti_HAV_IgM,
            HBeAg,
            Melioid_titer,
            CA_125,
            Ca_15_3,
            CA_19_9,
            AFP,
            CEA,
            PSA,
            B_HCG,
            Free_T4,
            Free_T3,
            TSH,
            Cortisol,
            Blood_Sugar,
            BUN,
            Creatinine,
            GFR,
            Uric_acid,
            Electrolyte_Na_Cl_K_CO2,
            HbAlC,
            Calcium,
            Phosphorus,
            Magnesium,
            Serum_Iron,
            TIBC,
            Ferritin,
            GGT,
            Cholesterol_LFT,
            Total_protein,
            Albumin,
            Direct_bilirubin,
            Total_bilirubin,
            AST_SGOT,
            ALT_SGPT,
            Alkaline_Phosphatase,
            Cholesterol_Lupid_Profile,
            Triglyceride,
            HDL_Cholesterol,
            LDL_Cholesterol,
            LDL_Direct,
            Creatinine_24_hrs,
            Protein_24_hrs,
            Creatinine_random,
            Protein_random,
            Microalbumin,
            Urine_Na_K_Cl,
            AFB_stain,
            Gram_stain,
            Hemo_I,
            Hemo_II,
            Sputum,
            PUS,
            Urine,
            RSC,
            Fluid,
            CSF,
            LDH,
            CPK,
            Amylase_Urine,
            Amylase_Serum,
            ADA_Urine,
            ADA_Serum,
            Osmolarity_Urine,
            Osmolarity_Serum,
            Ketone,
            Lipase,
            Transferin,
            Parathyroid,
            L_Lactate,
            Troponin_I,
            Prolactin,
            LH,
            FSH,
            Estradiol_E2,
            Insulin,
            Testosterone,
            Thyroglobulin,
            Anti_Thyroglobulin,
            Microsomal_Ab,
            Phenobarbital,
            PhenyItoin,
            Digoxin,
            Valproic,
            Carbamazepine,
            Vancomycin,
            NT_ProBNP,
            Chromosome_Study,
            Aldosterone,
            Renin,
            Anti_Smooth_Muscle,
            C_peptide,
            JAK2_gene_Mutation,
            HLA_B_5801,
            TSH_Recceptor_Ab,
            ANA_Profile,
            Vitamin_B12,
            Folate,
            Urine_VMA,
            Chikungunya_IgG_IgM,
            Rheumatoid_factor,
            C_Reactive_Protein,
            ASO,
            ANA_ANF_FANA,
            Anti_ds_DNA,
            Anti_Smith,
            Beta_1_C_C3c,
            C4_Complement,
            Crypto_Ag,
            Dengue_Ag_Ab,
            Scrub_typhus,
            Vitamin_D,
            HBV_Viral_load,
            HCV_Viral_load,
            HSV_PCR,
            CMV_PCR,
            TB_PCR,
            Anti_CCP,
            Anti_Car_IgG_IgM,
            Beta2_IgG_IgM,
            VDRL_CSF,
            D_dimer,
            Lupus_anticoagulant,
            LE_cell,
            Fetal_cell,
            OF_Test,
            DCIP,
            G_6_PD,
            Reticulocyte,
            Inclusion_body,
            Heinz_body,
            Hb_Typing,
            Anti_Cardiolipin_IgA,
            Beta2Glycoprotein_IgA,
            Anti_HAV_Total,
            Anti_HAB_IgG,
            Anti_HBe,
            Anti_thrombin_III,
            Protein_C,
            Protein_S,
            Anti_DNaseB,
            TB_culture,
            orderlab_id
        ];

        const result = await pool.query(query, values);
        
        if (result.rowCount === 0) {
            return res.status(404).json({
                success: false,
                message: 'LabTest not found',
            });
        }

        res.status(200).json({
            success: true,
            data: result.rows[0], // คืนค่าข้อมูล LabTest ที่ถูกอัปเดต
        });
    } catch (error) {
        console.error('Error updating LabTest:', error);
        res.status(500).json({
            success: false,
            message: 'Error updating LabTest',
            error: error.message,
        });
    }
}

//ยิง api สร้าง appoinement โดยตรง
export const DoctorAppointment = async (req,res) => {
    const {
        orderlab_id,
        member_id,
        cardd_id,
        app_appointdate,
        app_appointtime
    } = req.body;

    try {
        const client = await pool.connect();
        console.log('Connected to database');  // ตรวจสอบการเชื่อมต่อ

        const ress = await client.query('SELECT MAX(app_id) AS latest_id FROM appointment');
        const latestId = ress.rows[0].latest_id;
        const newId = (latestId || 0) + 1;

        const query = `
            INSERT INTO appointment (
                app_id,
                orderlab_id,
                member_id,
                card_id,
                app_appointdate,
                app_appointtime,
                app_acceptdate
            ) VALUES ($1, $2, $3, $4, $5, $6, current_timestamp ) RETURNING *;
        `;

        // Log the values being inserted
        const values = [
            newId,
            orderlab_id,
            member_id || null,
            cardd_id,
            app_appointdate,
            app_appointtime
        ];
        console.log('Inserting values:', values);
        
        const result = await client.query(query, values);
        res.status(201).json({
            success: true,
            data: result.rows[0],  // คืนค่าข้อมูลสมาชิกที่ถูกสร้าง
        });
        client.release();

    } catch (error) {
        console.error('Error creating appoinment:', error);  // ตรวจสอบข้อผิดพลาดจากการ insert ข้อมูล
        res.status(500).json({
            success: false,
            message: 'Error creating appoinment',
            error: error.message,
        });
    }
}

//path สร้าง orderselection แล้วหมอนัดเวลาต่อ
export const DoctorAppointmentt = async (newId, card_id, res) => {

    try {
        const client = await pool.connect();
        console.log('Connected to database');  // ตรวจสอบการเชื่อมต่อ

        const ress = await client.query('SELECT MAX(app_id) AS latest_id FROM appointment');
        const latestId = ress.rows[0].latest_id;
        const app_lastid = (latestId || 0) + 1;

        const query = `
            INSERT INTO appointment (
                app_id,
                orderlab_id,
                member_id,
                card_id,
                app_appointdate,
                app_appointtime,
                app_acceptdate
            ) VALUES ($1, $2, $3, $4, $5, $6, current_timestamp) RETURNING *;
        `;

        // Log the values being inserted
        const values = [
            app_lastid,
            newId,
            null,
            card_id,
            "2000-01-01",
            "00:00:00"
        ];
        console.log('Inserting values:', values);
        
        const result = await client.query(query, values);
        res.status(201).json({
            success: true,
            data: result.rows[0],  // คืนค่าข้อมูลสมาชิกที่ถูกสร้าง
        });

        client.release();
        return { newId,card_id };

    } catch (error) {
        console.error('Error creating order:', error);  // ตรวจสอบข้อผิดพลาดจากการ insert ข้อมูล
        res.status(500).json({
            success: false,
            message: 'Error creating order',
            error: error.message,
        });
    }
}

export const editAppointment = async (req,res) => {
    const { app_id } = req.params;
    const {
        member_id,
        app_appointdate,
        app_appointtime
    } = req.body;
    try {
        const query = `
            UPDATE appointment
            SET
                member_id = $1,
                app_appointdate = $2,
                app_appointtime = $3,
                app_acceptdate = current_timestamp
            WHERE app_id = $4
            RETURNING *;
        `;

        const values = [
            member_id || null,
            app_appointdate,
            app_appointtime,
            app_id
        ];

        const result = await pool.query(query, values);
        
        if (result.rowCount === 0) {
            return res.status(404).json({
                success: false,
                message: 'LabTest not found',
            });
        }

        res.status(200).json({
            success: true,
            data: result.rows[0], // คืนค่าข้อมูล LabTest ที่ถูกอัปเดต
        });
    } catch (error) {
        console.error('Error updating LabTest:', error);
        res.status(500).json({
            success: false,
            message: 'Error updating LabTest',
            error: error.message,
        });
    }
}

//สร้าง orderlab และ orderselection แบบ ลิงก์ orderalab_id pk กัน และแก้ไข orderselection ได้
export const handleCreateOrder = async (req,res) => {
    try {
        // สร้าง Order Lab และส่งค่ากลับ
        const { newId, card_id } = await createOrderLab(req, res);
        console.log('createOrderLab เสร็จแล้ว');

        // สร้าง Order Selection โดยใช้ค่าที่ส่งมา
        const orderSelection = await createOrderSelection(newId, card_id, res);
        console.log('createOrderSelection เสร็จแล้ว');

        const DoctorAppointmentt = await DoctorAppointmentt(newId, card_id, res);
        console.log('DoctorAppointmentt  เสร็จแล้ว');

        res.status(201).json({
            success: true,
            orderSelection,
            DoctorAppointmentt
        });

    } catch (error) {
        console.error('เกิดข้อผิดพลาด:', error);
        res.status(500).json({
            success: false,
            message: 'Error handling order creation',
            error: error.message,
        });
    }
};
