CREATE TABLE Loc_Items (
    LocItem_ID INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Item_ID INT NOT NULL,
    Employee_ID INT NOT NULL,
    Reception_ID INT NOT NULL,
    Loc_Status VARCHAR(200) NOT NULL,
    LocItems_DateUpdate TIMESTAMP,
    FOREIGN KEY (Item_ID) REFERENCES Items(Item_ID),
    FOREIGN KEY (Employee_ID) REFERENCES Employees(Employee_ID),
    FOREIGN KEY (Reception_ID) REFERENCES Reception(Reception_ID)
);

CREATE TABLE Loc_Package_item (
    LocItem_ID INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    PackageI_ID INT NOT NULL,
    Employee_ID INT NOT NULL,
    Reception_ID INT NOT NULL,
    Loc_Status VARCHAR(200) NOT NULL,
    LocItems_DateUpdate TIMESTAMP,
    FOREIGN KEY (PackageI_ID) REFERENCES Packageitem(PackageI_ID),
    FOREIGN KEY (Employee_ID) REFERENCES Employees(Employee_ID),
    FOREIGN KEY (Reception_ID) REFERENCES Reception(Reception_ID)
);

CREATE TABLE Loc_PacIDetail (
    Loc_PacIDetail_ID INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    PackageI_ID INT NOT NULL,
    Item_ID INT NOT NULL,
    Reception_ID INT NOT NULL,
    Employee_ID INT NOT NULL,
    Loc_Status VARCHAR(200) NOT NULL,
    LocRegi_DateUpdate TIMESTAMP,
    FOREIGN KEY (PackageI_ID) REFERENCES Packageitem(PackageI_ID),
    FOREIGN KEY (Item_ID) REFERENCES Items(Item_ID),
    FOREIGN KEY (Reception_ID) REFERENCES Reception(Reception_ID),
    FOREIGN KEY (Employee_ID) REFERENCES Employees(Employee_ID)
);

CREATE TABLE LocRecordLab (
    locRecordLab_ID INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    RecordLab_ID INT NOT NULL,
    Reception_ID INT NOT NULL,
    locRecordLab_Date TIMESTAMP NOT NULL,
    FOREIGN KEY (RecordLab_ID) REFERENCES RecordLab(RecordLab_ID),
    FOREIGN KEY (Reception_ID) REFERENCES Reception(Reception_ID)
);

CREATE TABLE Loc_PackLab (
    Loc_PacLab_ID INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    PackageLab_ID INT NOT NULL,
    Reception_ID INT NOT NULL,
    Employee_ID INT NOT NULL,
    Loc_Status VARCHAR(200) NOT NULL,
    LocRegi_DateUpdate TIMESTAMP,
    FOREIGN KEY (PackageLab_ID) REFERENCES PackageLab(PackageLab_ID),
    FOREIGN KEY (Reception_ID) REFERENCES Reception(Reception_ID),
    FOREIGN KEY (Employee_ID) REFERENCES Employees(Employee_ID)
);

CREATE TABLE Loc_RegisLab (
    LocRegis_ID INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    LabTest_ID INT NOT NULL,
    Reception_ID INT NOT NULL,
    Loc_Status VARCHAR(200) NOT NULL,
    LocRegi_DateUpdate TIMESTAMP,
    FOREIGN KEY (LabTest_ID) REFERENCES LabTest(LabTest_ID),
    FOREIGN KEY (Reception_ID) REFERENCES Reception(Reception_ID)
);

CREATE TABLE Loc_AcceptApp (
    LocAcp_ID INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Reception_ID INT NOT NULL,
    Acp_ID INT NOT NULL,
    Loc_Status VARCHAR(200) NOT NULL,
    LocAcp_AcceptDate TIMESTAMP,
    FOREIGN KEY (Reception_ID) REFERENCES Reception(Reception_ID),
    FOREIGN KEY (Acp_ID) REFERENCES Accept_Appointment(Acp_ID)
);

CREATE TABLE Loc_PacDetail (
    Loc_PackageDetail_ID INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    PackageLabDetail_ID INT NOT NULL,
    Reception_ID INT NOT NULL,
    Employee_ID INT NOT NULL,
    Loc_Status VARCHAR(200) NOT NULL,
    LocRegi_DateUpdate TIMESTAMP,
    FOREIGN KEY (PackageLabDetail_ID) REFERENCES PackageLabDetail(PackageLabDetail_ID),
    FOREIGN KEY (Reception_ID) REFERENCES Reception(Reception_ID),
    FOREIGN KEY (Employee_ID) REFERENCES Employees(Employee_ID)
);